package rules;

import com.sbnz.recovery.model.Patient;
import com.sbnz.recovery.model.enums.Gender;
import com.sbnz.recovery.model.ChosenPatient;
import com.sbnz.recovery.utility.DateUtility;

rule "Calculate BMR - Male"
	agenda-group "bmr-regular-calorie"
	salience 2
    when
        $cp: ChosenPatient( $chosenPatientId: chosenPatientId, resolved == false )
        $p: Patient( id == $chosenPatientId, gender == Gender.MALE, 
        	$height : height, $weight : weight, 
        	$age : DateUtility.getDiffYears(dateOfBirth) ) @Watch(!bmr)
    then
    	modify ($p) { setBmr(10 * $weight + 6.25 * $height - 5 * $age + 5); }
        System.out.println("Calculated BMR for MALE patient: " + $p.getBmr());
end

rule "Calculate BMR - Female"
	agenda-group "bmr-regular-calorie"
	salience 2
    when
        $cp: ChosenPatient( $chosenPatientId: chosenPatientId, resolved == false )
        $p: Patient( id == $chosenPatientId, gender == Gender.FEMALE, 
        	$height : height, $weight : weight, 
        	$age : DateUtility.getDiffYears(dateOfBirth) ) @Watch(!bmr)
    then
    	modify ($p) { setBmr(10 * $weight + 6.25 * $height - 5 * $age - 161); }
        System.out.println("Calculated BMR for FEMALE patient: " + $p.getBmr());
end
