package rules;

import java.util.Map;
import java.util.Set;
import java.util.List;

import com.sbnz.recovery.model.Patient;
import com.sbnz.recovery.model.Meal;
import com.sbnz.recovery.model.Ingredient;
import com.sbnz.recovery.model.IngredientAmount;
import com.sbnz.recovery.model.Illness;

global List<Meal> mealList;

rule "Rank meal for patient"
	agenda-group "rank-meal"
	salience $goodIngredientCount
	when
		$cp: ChosenPatient($chosenPatientId: chosenPatientId, resolved == false)
		$p: Patient(id == $chosenPatientId, $anamnesis: anamnesis)
		$m: Meal($ingredients : ingredients, $mealName : name)
        $goodIngredientCount : Number($anamnesis.size() == 0 || intValue >= $ingredients.size() / 2) from accumulate(
        	IngredientAmount($i : ingredient, $illnesses : ingredient.illnesses) from $ingredients and
        	$matchedIllnessCount : Number(intValue >= $illnesses.size() / 2) from accumulate(
	        	Illness($illness : this) from $illnesses
				and Illness(this.id == $illness.id) from $anamnesis,
				count($illness)
			),
        	count($matchedIllnessCount)
        )
	then
		//modify ($cp) { setResolved(true); }
        mealList.add($m);
		System.out.println("Added meal " + $mealName + 
		" for patient " + $p.getUsername() + 
		" with number of good ingredients: " + $goodIngredientCount);
end


rule "Resolve unresolved"
	agenda-group "rank-meal"
	salience -1
	when
		$cp: ChosenPatient($chosenPatientId: chosenPatientId, resolved == false)
	then
		modify ($cp) { setResolved(true); }
end