package rules;

import com.sbnz.recovery.model.Patient;
import com.sbnz.recovery.model.enums.Gender;
import com.sbnz.recovery.model.enums.PhysicalActivity;
import com.sbnz.recovery.model.enums.Gender;
import com.sbnz.recovery.model.ChosenPatient;

/*
 * Sedentary (little or no exercise) : Calorie-Calculation = BMR x 1.2
 * Lightly active (light exercise/sports 1-3 days/week) : Calorie-Calculation = BMR x 1.375
 * Moderately active (moderate exercise/sports 3-5 days/week) : Calorie-Calculation = BMR x 1.55
 * Very active (hard exercise/sports 6-7 days a week) : Calorie-Calculation = BMR x 1.725
 * Extra active (very hard exercise/sports & a physical job) : Calorie-Calculation = BMR x 1.9
*/

rule "Calculate Regular Daily Calorie Intake - SENDENTARY"
	agenda-group "bmr-regular-calorie"
	salience 1
    when
        $cp: ChosenPatient( $chosenPatientId: chosenPatientId, resolved == false )
        $p: Patient( id == $chosenPatientId,
        	physicalActivityBeforeInjury == PhysicalActivity.SEDENTARY, 
        	$bmr : bmr ) @Watch(!regularDailyCaloryIntake)
    then
    	modify ($p) { setRegularDailyCaloryIntake($bmr * 1.2); }
        System.out.println("Calculated Regular Daily Calorie Intake for SENDENTARY patient: " + $p.getRegularDailyCaloryIntake());
end

rule "Calculate Regular Daily Calorie Intake - LIGHT_ACTIVE"
	agenda-group "bmr-regular-calorie"
	salience 1
    when
        $cp: ChosenPatient( $chosenPatientId: chosenPatientId, resolved == false )
        $p: Patient( id == $chosenPatientId,
        	physicalActivityBeforeInjury == PhysicalActivity.LIGHT_ACTIVE, 
        	$bmr : bmr ) @Watch(!regularDailyCaloryIntake)
    then
    	modify ($p) { setRegularDailyCaloryIntake($bmr * 1.375); }
        System.out.println("Calculated Regular Daily Calorie Intake for LIGHT_ACTIVE patient: " + $p.getRegularDailyCaloryIntake());
end

rule "Calculate Regular Daily Calorie Intake - MODERATE"
	agenda-group "bmr-regular-calorie"
	salience 1
    when
        $cp: ChosenPatient( $chosenPatientId: chosenPatientId, resolved == false )
        $p: Patient( id == $chosenPatientId,
        	physicalActivityBeforeInjury == PhysicalActivity.MODERATE, 
        	$bmr : bmr ) @Watch(!regularDailyCaloryIntake)
    then
    	modify ($p) { setRegularDailyCaloryIntake($bmr * 1.55); }
        System.out.println("Calculated Regular Daily Calorie Intake for MODERATE patient: " + $p.getRegularDailyCaloryIntake());
end

rule "Calculate Regular Daily Calorie Intake - VERY_ACTIVE"
	agenda-group "bmr-regular-calorie"
	salience 1
    when
        $cp: ChosenPatient( $chosenPatientId: chosenPatientId, resolved == false )
        $p: Patient( id == $chosenPatientId,
        	physicalActivityBeforeInjury == PhysicalActivity.VERY_ACTIVE, 
        	$bmr : bmr ) @Watch(!regularDailyCaloryIntake)
    then
    	modify ($p) { setRegularDailyCaloryIntake($bmr * 1.725); }
        System.out.println("Calculated Regular Daily Calorie Intake for VERY_ACTIVE patient: " + $p.getRegularDailyCaloryIntake());
end

rule "Calculate Regular Daily Calorie Intake - EXTRA_ACTIVE"
	agenda-group "bmr-regular-calorie"
	salience 1
    when
        $cp: ChosenPatient( $chosenPatientId: chosenPatientId, resolved == false )
        $p: Patient( id == $chosenPatientId,
        	physicalActivityBeforeInjury == PhysicalActivity.EXTRA_ACTIVE, 
        	$bmr : bmr ) @Watch(!regularDailyCaloryIntake)
    then
    	modify ($p) { setRegularDailyCaloryIntake($bmr * 1.9); }
        System.out.println("Calculated Regular Daily Calorie Intake for EXTRA_ACTIVE patient: " + $p.getRegularDailyCaloryIntake());
end

rule "Change agenda-group to new-activity-level"
	agenda-group "bmr-regular-calorie"
	salience -1
	when
		ChosenPatient( resolved == false )
		//Patient(id == )
	then
		System.out.println("Changed agenda-group from bmr-regular-calorie to new-activity-level");
		kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("new-activity-level").setFocus();
end