package rules;

import com.sbnz.recovery.model.Therapy;
import com.sbnz.recovery.model.InjuryType;
import com.sbnz.recovery.model.enums.TherapyType;
import com.sbnz.recovery.model.Illness;

// injuries
rule "Therapy FRACTURE"
	lock-on-active true
	agenda-group "classify-therapy"
    when
        $t: Therapy(therapyType != TherapyType.KINESIOTHERAPY, intensity < 6)
        $fracture: InjuryType(name == "Fracture")
    then
    	modify ($t) { addApplicableInjuryType($fracture); }
        System.out.println("Therapy applicable for FRACTURE");
end

rule "Therapy MUSCLE_STRAIN"
	lock-on-active true
	agenda-group "classify-therapy"
    when
        $t: Therapy(temperature < 15.0)
        $muscle: InjuryType(name == "Muscle strain")
    then
    	modify ($t) { addApplicableInjuryType($muscle); }
        System.out.println("Therapy applicable for MUSCLE_STRAIN");
end

rule "Therapy INTERNAL"
	lock-on-active true
	agenda-group "classify-therapy"
    when
        $t: Therapy(intensity < 3, therapyType != TherapyType.KINESIOTHERAPY)
        $internal: InjuryType(name == "Internal")
    then
    	modify ($t) { addApplicableInjuryType($internal); }
        System.out.println("Therapy applicable for INTERNAL");
end

// illnesses
rule "Therapy DIABETES"
	lock-on-active true
	agenda-group "classify-therapy"
    when
        $t: Therapy(intensity < 7)
        $diabetes: Illness(name == "Diabetes")
    then
    	modify ($t) { addApplicableIllness($diabetes); }
        System.out.println("Therapy applicable for DIABETES");
end

rule "Therapy HIGH_BLOOD_PRESSURE"
	lock-on-active true
	agenda-group "classify-therapy"
    when
        $t: Therapy(temperature < 25.0, intensity < 6)
        $hbp: Illness(name == "High blood pressure")
    then
    	modify ($t) { addApplicableIllness($hbp); }
        System.out.println("Therapy applicable for HIGH_BLOOD_PRESSURE");
end

rule "Therapy LOW_BLOOD_PRESSURE"
	lock-on-active true
	agenda-group "classify-therapy"
    when
        $t: Therapy(therapyType != TherapyType.MAGNET)
        $lbp: Illness(name == "Low blood pressure")
    then
    	modify ($t) { addApplicableIllness($lbp); }
        System.out.println("Therapy applicable for LOW_BLOOD_PRESSURE");
end

/*rule "Therapy REST"
	lock-on-active true
	agenda-group "classify-therapy"
	when
		$t: Therapy(therapyType == TherapyType.REST)
		$it: InjuryType(name == "Internal")
		$il: Illness(name == "Low blood pressure")
	then
		modify($t) { addApplicableIllness($il),
					addApplicableInjuryType($it); }
        System.out.println("Therapy REST applicable for everything");
end*/
